import React from "react";

export default function ReportCard({ report }){
  if(!report) return null;
  const s = report.summary || {};
  return (
    <div style={{border:"1px solid #ddd", padding:12, borderRadius:6, marginBottom:10}}>
      <div><strong>Commit:</strong> {report.commit_id}</div>
      <div><strong>Branch:</strong> {report.branch}</div>
      <div><strong>Ready for regression:</strong> {s.build_ready_for_regression ? "Yes" : "No"}</div>
      <div><strong>Syntax Errors:</strong> {Array.isArray(s.syntax_errors) ? s.syntax_errors.map(x=> x.file+":"+x.error).join("; ") : s.syntax_errors}</div>
      <div><strong>Missing Functions:</strong> {Array.isArray(s.missing_functions) ? s.missing_functions.map(x=> x.file + ":" + (x.missing||[]).join(",")).join("; ") : ""}</div>
      <div><strong>UI Issues:</strong> {JSON.stringify(s.ui_issues)}</div>
      <div style={{marginTop:8, color:"#666"}}><small>Report generated by Gemini analysis</small></div>
    </div>
  );
}
